### ISSUE TITLE
Great book! But some chapters are not rigorous.

### ISSUE THREAD

**Issue by xiezhuojin** [tinyclub/open-c-book#11]
从这本书学到了很多，暂时看到动态链接那节，收获良多！但是在第九节中我觉得不够严谨，比如说got并不一定需要plt一起才能其中用的，我从这篇文章https://www.bottomupcs.com/global_offset_tables.xhtml
了解到got表是为了减轻动态链接的负担单独拿出来的，还有是为了不修改代码，而plt是为了lazy binding。第九章我看了差不多三遍了，也不是很懂，最后看那篇文章就明白了。BTW，我在你的vim章节那学到不少，特别是shift+k可以直接看manpage，请问有没有更多vim中关于C编程的技巧呢？比如说header跳转什么的。

**Comment by lzufalcon** [comment]
@xiezhuojin 谢谢分享阅读体会，接下来我再看看 plt 部分。欢迎加微信 lzufalcon 进一步沟通。
